### ISSUE TITLE
Adding Feature

### ISSUE THREAD

**Issue by saikoostark** [luanon404/seledroid-drivers#15]
Can you please add pop up window and web tabs

**Comment by luanon404** [comment]
i tried it already, but it doesn't seem right, i don't know how other browsers do it, but with me it's a mess, i will try again, but it will cost too much time

**Comment by saikoostark** [comment]
@luanon404 
i am sorry , but how did you connect seledroid with your browser ?

**Comment by luanon404** [comment]
> @luanon404 i am sorry , but how did you connect seledroid with your browser ?

use socket to send and recv data, chromium is my self make app written by java use WebChromeClient and WebViewClient to make, it is not chrome, because its my self make so its a big problem, i dont know to much about java and something like that, just a code language i learn when boring. I will post the source soon, so you can make it if you want but its very terrible.

**Comment by luanon404** [comment]
I use a lot of hacks to fix a lot of stupid bugs, so be careful when editing some places and most importantly **don't edit the build.gradle file**

**Comment by luanon404** [comment]
https://github.com/luanon404/seledroid-drivers/tree/main/Chromium

**Comment by luanon404** [comment]
> Can you please add pop up window and web tabs

Your request has been accepted 😄
Join my [telegram group](https://t.me/RHToolCommunity) for more imformation.
